-- Per-ghost model alias override.
-- Stores a JSON-encoded ModelAliases (single string or list) so each ghost can
-- use a different model chain than the global default_model.
--
-- No-op: model_aliases was folded into the unified schema
-- (20260210000000_unified_schema.sql). Kept for migration ordering.
